language: python
script:
- echo "no tests"
deploy:
  provider: pypi
  user: Guewen.Baconnier
  password:
    secure: Qbr1wxL/fdJpf3pCS+pq/mrVKZ5MzhXu7sVYVJ+P00VTw/13G3WwBK11gsd1HgbNpeai103X6yKcJj94S90scrF1kOHMSYMTTdZmHa16CFheeKthayX6vcuHQLUZaolVE8BddW77lor6mbEnA7e5Hknlq8+F5PnAPLwmCYM6kiQNbFjA2yuKcTsfpEfle/wh4NvbgHMXUBKz6AknY8O8GFG/6OqbTjBOY8WXBYueF+MdhhfejmniMawkReJjQNqlsB60LH94PK2Sh02iV5urmF0AdrDANS/8+dfU3VYA0MhRVN+Lbqk6O8ZL8gLFWtJvJG+xfqWRFvFMm1n3wLCsZwQeO76VwXMWcRE/IYqNPs4U8LmKf/ndacgdyvjXemjMJ46ZONQu9bPxnE04wJzr2FKkmsuYYwt8IQu5OGjThgvoZLoCKeTTQeY7PizyXaArZIBHLCPkhQ1f6M37wgNrVdm+OAffaJ8ObZVs+hnmnRuIncyC8xfRck1sB6MeF3YA3xxnEJg/z9/74OeqHBkzlwzgEvNjcR9aFmqy8WwisJWSQ6/pQAALLu6NkvG1zvslQv+MRv+DqkZmeBfj1M8FexnrFZHJlQMUQOG52hakWGVBtVyXbeHSmp3c3HpLZrLDVPIpjbh9EPc3S8vV9YkqoZtkh1R3ArRlAeyflLH0yuo=
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/pytest-odoo
    branch: master
    tags: true
