language: python
script:
- echo "no tests"
deploy:
  provider: pypi
  user: Guewen.Baconnier
  password:
    secure: IQPNE4LPj4yjo+JgvIruEmTVuJdjg1MxwDL0SAnhmEESHeZrg+K2kBZmJUddm2l8v/c6h6mel9j5QlLZg5y/23ZKA0CMCmtmnV2iz38hO+tlZfGOE3fEmMUEKk9VTZaafobBl3uFVMq1LRhvv/MkRAVS15yZddMpylak5BjbgnSTlRtE8VxzPFQzr6FFeik9tjVqlfcV+vfMcWhMlECh414P/VnTK2LfTb5oVnJNhGSuY1ctGkV4q6nigqJbwlY2bB/w0nFzh2TRHXigx9F6oUXeWLsoOYQmyi6WwDR9DbcdSa1u1vcHuYQzeaC6Syz1f9Bm11iibEJhbk7AjDOpQ2zLPruFFrUB7UstIDHNgnG9Y2NpUKS2IRiF2ETR+AzkPOyrp5jCj9UAfau75jonpdV48jp4dwLvMhowFmVXubwMlVmXA2W0EquOk7AymM3MvVYRBrZfzxTee2ySLH/1yrWACi16L95xZ0u17hsb+6stMcPKT1MZkgHquvqw128pgGJkaP+m+1THAEMCXk4YGZ7nHDxb+OrgWweswXZ04HRhJEGVYP840XCL7Tr17hggnpjTbNzT7y/D7Ou675LK0brm4r7sb0DrugPPxAvzbY/C9zjmzh+Lh4XtwyScDpgp3vUCn8KemAyl3X5EtTASAXnExF2jwmW5FgeqvPiJCdg=
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/pytest-odoo
    branch: master
    tags: true
