language: python
script:
- echo "no tests"
deploy:
  provider: pypi
  user: Guewen.Baconnier
  password:
    secure: B3IiDTKLRnJ2Oo19QugbNViaD58AHEjE7fkf9zZxfSuiIGyW2Ft+ri7V/HcwRmoVC6wXJ8vP9cg3YRl0lWRWO3RVZomo5xW7e+Jbh5ihD/RN9VsvlUtRCis7zwevAz+WVRXwse3so76TJ7a2HCwskgGUeC4l0bX+maIZ5fHD/MAG5zlQeUqO0WTh9w1bB6RoQtVgHSAMQiZwRrjTWRhhUWsxtL9m2lVlSn4Si5/LDBhuxb6VZ5Q2ShCz/jUhkXVD1U0UBhzTdawnK+j33Us7Xnt6zUqMN3PgPkRJQKpuVHvt6aN7C9APxxCE+iS0eYfmMJyZFnsBOPgER3HMEM+5Aub62JsFPPM6e4aLSMuGQ+D21xlLzpCwcWBj88LqxFaXphIvuo/CXmK9wAdTlTiebOHsSkOVDO3MP1EyFnbqbPEnUg4i6AaoByANysNN6NKGHD9j1w0/HX3NPveVP+e3sgRoCVyc1QbFwihGvCO2XoV7MYylN9D+i9345GIzezfYd8rGcVVySPKbxXIl/+evJa8smrdVk9eSN6J1hpnU/c6HVlzi0TgxKyEhaHvS4zwY3xeCC/kKqq9XWdac+vaPDlTGyjOhQGnFX6LsnvG1QLWNNRXV6vd8jMZAxMv32TgUUCu9wwEsaXRmuqZvGUTt8fZtrl792vbI7qksKqb1ncA=
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/pytest-odoo
    branch: master
    tags: true
