language: python
script:
- echo "no tests"
deploy:
  provider: pypi
  user: Guewen.Baconnier
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/pytest-odoo
    branch: fix-pypi
    tags: true
